//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuangCao
    {
        public int QuangCaoID { get; set; }
        public string TenCongTy { get; set; }
        public string HinhQuangCao { get; set; }
        public string DiaChiWS { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    }
}
