//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public Sach()
        {
            this.DatHangCTs = new HashSet<DatHangCT>();
            this.ThamGias = new HashSet<ThamGia>();
            this.PhieuNhapCTs = new HashSet<PhieuNhapCT>();
        }
    
        public int SachID { get; set; }
        public string TenSach { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<int> ChuDeID { get; set; }
        public Nullable<int> NhaXuatBanID { get; set; }
        public string MoTa { get; set; }
        public string HinhBia { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public Nullable<int> TrongLuong { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> SoLanXem { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public bool HetHang { get; set; }
        public Nullable<int> DaBan { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ChuDe ChuDe { get; set; }
        public virtual ICollection<DatHangCT> DatHangCTs { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual ICollection<ThamGia> ThamGias { get; set; }
        public virtual ICollection<PhieuNhapCT> PhieuNhapCTs { get; set; }
    }
}
