//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sach", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    [System.SerializableAttribute()]
    public partial class Sach : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApp.ServiceReference1.ChuDe ChuDeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ChuDeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DaBanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebApp.ServiceReference1.DatHangCT> DatHangCTsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> GiaBanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HetHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HinhBiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoTaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayCapNhatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApp.ServiceReference1.NhaXuatBan NhaXuatBanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NhaXuatBanIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebApp.ServiceReference1.PhieuNhapCT> PhieuNhapCTsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SachIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SoLanXemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SoLuongBanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SoTrangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSachField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebApp.ServiceReference1.ThamGia> ThamGiasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TrongLuongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApp.ServiceReference1.ChuDe ChuDe {
            get {
                return this.ChuDeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChuDeField, value) != true)) {
                    this.ChuDeField = value;
                    this.RaisePropertyChanged("ChuDe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ChuDeID {
            get {
                return this.ChuDeIDField;
            }
            set {
                if ((this.ChuDeIDField.Equals(value) != true)) {
                    this.ChuDeIDField = value;
                    this.RaisePropertyChanged("ChuDeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DaBan {
            get {
                return this.DaBanField;
            }
            set {
                if ((this.DaBanField.Equals(value) != true)) {
                    this.DaBanField = value;
                    this.RaisePropertyChanged("DaBan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebApp.ServiceReference1.DatHangCT> DatHangCTs {
            get {
                return this.DatHangCTsField;
            }
            set {
                if ((object.ReferenceEquals(this.DatHangCTsField, value) != true)) {
                    this.DatHangCTsField = value;
                    this.RaisePropertyChanged("DatHangCTs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> GiaBan {
            get {
                return this.GiaBanField;
            }
            set {
                if ((this.GiaBanField.Equals(value) != true)) {
                    this.GiaBanField = value;
                    this.RaisePropertyChanged("GiaBan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HetHang {
            get {
                return this.HetHangField;
            }
            set {
                if ((this.HetHangField.Equals(value) != true)) {
                    this.HetHangField = value;
                    this.RaisePropertyChanged("HetHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HinhBia {
            get {
                return this.HinhBiaField;
            }
            set {
                if ((object.ReferenceEquals(this.HinhBiaField, value) != true)) {
                    this.HinhBiaField = value;
                    this.RaisePropertyChanged("HinhBia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoTa {
            get {
                return this.MoTaField;
            }
            set {
                if ((object.ReferenceEquals(this.MoTaField, value) != true)) {
                    this.MoTaField = value;
                    this.RaisePropertyChanged("MoTa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayCapNhat {
            get {
                return this.NgayCapNhatField;
            }
            set {
                if ((this.NgayCapNhatField.Equals(value) != true)) {
                    this.NgayCapNhatField = value;
                    this.RaisePropertyChanged("NgayCapNhat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApp.ServiceReference1.NhaXuatBan NhaXuatBan {
            get {
                return this.NhaXuatBanField;
            }
            set {
                if ((object.ReferenceEquals(this.NhaXuatBanField, value) != true)) {
                    this.NhaXuatBanField = value;
                    this.RaisePropertyChanged("NhaXuatBan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NhaXuatBanID {
            get {
                return this.NhaXuatBanIDField;
            }
            set {
                if ((this.NhaXuatBanIDField.Equals(value) != true)) {
                    this.NhaXuatBanIDField = value;
                    this.RaisePropertyChanged("NhaXuatBanID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebApp.ServiceReference1.PhieuNhapCT> PhieuNhapCTs {
            get {
                return this.PhieuNhapCTsField;
            }
            set {
                if ((object.ReferenceEquals(this.PhieuNhapCTsField, value) != true)) {
                    this.PhieuNhapCTsField = value;
                    this.RaisePropertyChanged("PhieuNhapCTs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SachID {
            get {
                return this.SachIDField;
            }
            set {
                if ((this.SachIDField.Equals(value) != true)) {
                    this.SachIDField = value;
                    this.RaisePropertyChanged("SachID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SoLanXem {
            get {
                return this.SoLanXemField;
            }
            set {
                if ((this.SoLanXemField.Equals(value) != true)) {
                    this.SoLanXemField = value;
                    this.RaisePropertyChanged("SoLanXem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SoLuongBan {
            get {
                return this.SoLuongBanField;
            }
            set {
                if ((this.SoLuongBanField.Equals(value) != true)) {
                    this.SoLuongBanField = value;
                    this.RaisePropertyChanged("SoLuongBan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SoTrang {
            get {
                return this.SoTrangField;
            }
            set {
                if ((this.SoTrangField.Equals(value) != true)) {
                    this.SoTrangField = value;
                    this.RaisePropertyChanged("SoTrang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenSach {
            get {
                return this.TenSachField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSachField, value) != true)) {
                    this.TenSachField = value;
                    this.RaisePropertyChanged("TenSach");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebApp.ServiceReference1.ThamGia> ThamGias {
            get {
                return this.ThamGiasField;
            }
            set {
                if ((object.ReferenceEquals(this.ThamGiasField, value) != true)) {
                    this.ThamGiasField = value;
                    this.RaisePropertyChanged("ThamGias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TrongLuong {
            get {
                return this.TrongLuongField;
            }
            set {
                if ((this.TrongLuongField.Equals(value) != true)) {
                    this.TrongLuongField = value;
                    this.RaisePropertyChanged("TrongLuong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChuDe", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    [System.SerializableAttribute()]
    public partial class ChuDe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChuDeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebApp.ServiceReference1.Sach> SachesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenChuDeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChuDeID {
            get {
                return this.ChuDeIDField;
            }
            set {
                if ((this.ChuDeIDField.Equals(value) != true)) {
                    this.ChuDeIDField = value;
                    this.RaisePropertyChanged("ChuDeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebApp.ServiceReference1.Sach> Saches {
            get {
                return this.SachesField;
            }
            set {
                if ((object.ReferenceEquals(this.SachesField, value) != true)) {
                    this.SachesField = value;
                    this.RaisePropertyChanged("Saches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenChuDe {
            get {
                return this.TenChuDeField;
            }
            set {
                if ((object.ReferenceEquals(this.TenChuDeField, value) != true)) {
                    this.TenChuDeField = value;
                    this.RaisePropertyChanged("TenChuDe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NhaXuatBan", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    [System.SerializableAttribute()]
    public partial class NhaXuatBan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NhaXuatBanIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebApp.ServiceReference1.Sach> SachesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNhaXuatBanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DienThoai {
            get {
                return this.DienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.DienThoaiField, value) != true)) {
                    this.DienThoaiField = value;
                    this.RaisePropertyChanged("DienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NhaXuatBanID {
            get {
                return this.NhaXuatBanIDField;
            }
            set {
                if ((this.NhaXuatBanIDField.Equals(value) != true)) {
                    this.NhaXuatBanIDField = value;
                    this.RaisePropertyChanged("NhaXuatBanID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebApp.ServiceReference1.Sach> Saches {
            get {
                return this.SachesField;
            }
            set {
                if ((object.ReferenceEquals(this.SachesField, value) != true)) {
                    this.SachesField = value;
                    this.RaisePropertyChanged("Saches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNhaXuatBan {
            get {
                return this.TenNhaXuatBanField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNhaXuatBanField, value) != true)) {
                    this.TenNhaXuatBanField = value;
                    this.RaisePropertyChanged("TenNhaXuatBan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatHangCT", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    [System.SerializableAttribute()]
    public partial class DatHangCT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApp.ServiceReference1.DatHang DatHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DatHangIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> DonGiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApp.ServiceReference1.Sach SachField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SachIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SoLuongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> ThanhTienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApp.ServiceReference1.DatHang DatHang {
            get {
                return this.DatHangField;
            }
            set {
                if ((object.ReferenceEquals(this.DatHangField, value) != true)) {
                    this.DatHangField = value;
                    this.RaisePropertyChanged("DatHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DatHangID {
            get {
                return this.DatHangIDField;
            }
            set {
                if ((this.DatHangIDField.Equals(value) != true)) {
                    this.DatHangIDField = value;
                    this.RaisePropertyChanged("DatHangID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> DonGia {
            get {
                return this.DonGiaField;
            }
            set {
                if ((this.DonGiaField.Equals(value) != true)) {
                    this.DonGiaField = value;
                    this.RaisePropertyChanged("DonGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApp.ServiceReference1.Sach Sach {
            get {
                return this.SachField;
            }
            set {
                if ((object.ReferenceEquals(this.SachField, value) != true)) {
                    this.SachField = value;
                    this.RaisePropertyChanged("Sach");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SachID {
            get {
                return this.SachIDField;
            }
            set {
                if ((this.SachIDField.Equals(value) != true)) {
                    this.SachIDField = value;
                    this.RaisePropertyChanged("SachID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ThanhTien {
            get {
                return this.ThanhTienField;
            }
            set {
                if ((this.ThanhTienField.Equals(value) != true)) {
                    this.ThanhTienField = value;
                    this.RaisePropertyChanged("ThanhTien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhieuNhapCT", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    [System.SerializableAttribute()]
    public partial class PhieuNhapCT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> DonGiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDPhieuNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDSachField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApp.ServiceReference1.PhieuNhap PhieuNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApp.ServiceReference1.Sach SachField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SoLuongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> ThanhTienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> DonGia {
            get {
                return this.DonGiaField;
            }
            set {
                if ((this.DonGiaField.Equals(value) != true)) {
                    this.DonGiaField = value;
                    this.RaisePropertyChanged("DonGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDPhieuNhap {
            get {
                return this.IDPhieuNhapField;
            }
            set {
                if ((this.IDPhieuNhapField.Equals(value) != true)) {
                    this.IDPhieuNhapField = value;
                    this.RaisePropertyChanged("IDPhieuNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDSach {
            get {
                return this.IDSachField;
            }
            set {
                if ((this.IDSachField.Equals(value) != true)) {
                    this.IDSachField = value;
                    this.RaisePropertyChanged("IDSach");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApp.ServiceReference1.PhieuNhap PhieuNhap {
            get {
                return this.PhieuNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.PhieuNhapField, value) != true)) {
                    this.PhieuNhapField = value;
                    this.RaisePropertyChanged("PhieuNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApp.ServiceReference1.Sach Sach {
            get {
                return this.SachField;
            }
            set {
                if ((object.ReferenceEquals(this.SachField, value) != true)) {
                    this.SachField = value;
                    this.RaisePropertyChanged("Sach");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ThanhTien {
            get {
                return this.ThanhTienField;
            }
            set {
                if ((this.ThanhTienField.Equals(value) != true)) {
                    this.ThanhTienField = value;
                    this.RaisePropertyChanged("ThanhTien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThamGia", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    [System.SerializableAttribute()]
    public partial class ThamGia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApp.ServiceReference1.Sach SachField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SachIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApp.ServiceReference1.TacGia TacGiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TacGiaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VaiTroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ViTriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApp.ServiceReference1.Sach Sach {
            get {
                return this.SachField;
            }
            set {
                if ((object.ReferenceEquals(this.SachField, value) != true)) {
                    this.SachField = value;
                    this.RaisePropertyChanged("Sach");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SachID {
            get {
                return this.SachIDField;
            }
            set {
                if ((this.SachIDField.Equals(value) != true)) {
                    this.SachIDField = value;
                    this.RaisePropertyChanged("SachID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApp.ServiceReference1.TacGia TacGia {
            get {
                return this.TacGiaField;
            }
            set {
                if ((object.ReferenceEquals(this.TacGiaField, value) != true)) {
                    this.TacGiaField = value;
                    this.RaisePropertyChanged("TacGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TacGiaID {
            get {
                return this.TacGiaIDField;
            }
            set {
                if ((this.TacGiaIDField.Equals(value) != true)) {
                    this.TacGiaIDField = value;
                    this.RaisePropertyChanged("TacGiaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VaiTro {
            get {
                return this.VaiTroField;
            }
            set {
                if ((object.ReferenceEquals(this.VaiTroField, value) != true)) {
                    this.VaiTroField = value;
                    this.RaisePropertyChanged("VaiTro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ViTri {
            get {
                return this.ViTriField;
            }
            set {
                if ((this.ViTriField.Equals(value) != true)) {
                    this.ViTriField = value;
                    this.RaisePropertyChanged("ViTri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatHang", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    [System.SerializableAttribute()]
    public partial class DatHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DaGiaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebApp.ServiceReference1.DatHangCT> DatHangCTsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DatHangIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaDiemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApp.ServiceReference1.KhachHang KhachHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KhachHangIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayDatHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayGiaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhachHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> TriGiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DaGiao {
            get {
                return this.DaGiaoField;
            }
            set {
                if ((this.DaGiaoField.Equals(value) != true)) {
                    this.DaGiaoField = value;
                    this.RaisePropertyChanged("DaGiao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebApp.ServiceReference1.DatHangCT> DatHangCTs {
            get {
                return this.DatHangCTsField;
            }
            set {
                if ((object.ReferenceEquals(this.DatHangCTsField, value) != true)) {
                    this.DatHangCTsField = value;
                    this.RaisePropertyChanged("DatHangCTs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DatHangID {
            get {
                return this.DatHangIDField;
            }
            set {
                if ((this.DatHangIDField.Equals(value) != true)) {
                    this.DatHangIDField = value;
                    this.RaisePropertyChanged("DatHangID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaDiem {
            get {
                return this.DiaDiemField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaDiemField, value) != true)) {
                    this.DiaDiemField = value;
                    this.RaisePropertyChanged("DiaDiem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApp.ServiceReference1.KhachHang KhachHang {
            get {
                return this.KhachHangField;
            }
            set {
                if ((object.ReferenceEquals(this.KhachHangField, value) != true)) {
                    this.KhachHangField = value;
                    this.RaisePropertyChanged("KhachHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KhachHangID {
            get {
                return this.KhachHangIDField;
            }
            set {
                if ((this.KhachHangIDField.Equals(value) != true)) {
                    this.KhachHangIDField = value;
                    this.RaisePropertyChanged("KhachHangID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgayDatHang {
            get {
                return this.NgayDatHangField;
            }
            set {
                if ((this.NgayDatHangField.Equals(value) != true)) {
                    this.NgayDatHangField = value;
                    this.RaisePropertyChanged("NgayDatHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgayGiao {
            get {
                return this.NgayGiaoField;
            }
            set {
                if ((this.NgayGiaoField.Equals(value) != true)) {
                    this.NgayGiaoField = value;
                    this.RaisePropertyChanged("NgayGiao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenKhachHang {
            get {
                return this.TenKhachHangField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhachHangField, value) != true)) {
                    this.TenKhachHangField = value;
                    this.RaisePropertyChanged("TenKhachHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TriGia {
            get {
                return this.TriGiaField;
            }
            set {
                if ((this.TriGiaField.Equals(value) != true)) {
                    this.TriGiaField = value;
                    this.RaisePropertyChanged("TriGia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KhachHang", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    [System.SerializableAttribute()]
    public partial class KhachHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> AdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebApp.ServiceReference1.DatHang> DatHangsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KhachHangIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatKhauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDangNhapField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Admin {
            get {
                return this.AdminField;
            }
            set {
                if ((this.AdminField.Equals(value) != true)) {
                    this.AdminField = value;
                    this.RaisePropertyChanged("Admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebApp.ServiceReference1.DatHang> DatHangs {
            get {
                return this.DatHangsField;
            }
            set {
                if ((object.ReferenceEquals(this.DatHangsField, value) != true)) {
                    this.DatHangsField = value;
                    this.RaisePropertyChanged("DatHangs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DienThoai {
            get {
                return this.DienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.DienThoaiField, value) != true)) {
                    this.DienThoaiField = value;
                    this.RaisePropertyChanged("DienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((this.GioiTinhField.Equals(value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KhachHangID {
            get {
                return this.KhachHangIDField;
            }
            set {
                if ((this.KhachHangIDField.Equals(value) != true)) {
                    this.KhachHangIDField = value;
                    this.RaisePropertyChanged("KhachHangID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatKhau {
            get {
                return this.MatKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.MatKhauField, value) != true)) {
                    this.MatKhauField = value;
                    this.RaisePropertyChanged("MatKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDangNhap {
            get {
                return this.TenDangNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDangNhapField, value) != true)) {
                    this.TenDangNhapField = value;
                    this.RaisePropertyChanged("TenDangNhap");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhieuNhap", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    [System.SerializableAttribute()]
    public partial class PhieuNhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebApp.ServiceReference1.PhieuNhapCT> PhieuNhapCTsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> TongTienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgayNhap {
            get {
                return this.NgayNhapField;
            }
            set {
                if ((this.NgayNhapField.Equals(value) != true)) {
                    this.NgayNhapField = value;
                    this.RaisePropertyChanged("NgayNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebApp.ServiceReference1.PhieuNhapCT> PhieuNhapCTs {
            get {
                return this.PhieuNhapCTsField;
            }
            set {
                if ((object.ReferenceEquals(this.PhieuNhapCTsField, value) != true)) {
                    this.PhieuNhapCTsField = value;
                    this.RaisePropertyChanged("PhieuNhapCTs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TongTien {
            get {
                return this.TongTienField;
            }
            set {
                if ((this.TongTienField.Equals(value) != true)) {
                    this.TongTienField = value;
                    this.RaisePropertyChanged("TongTien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TacGia", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    [System.SerializableAttribute()]
    public partial class TacGia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TacGiaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenTacGiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebApp.ServiceReference1.ThamGia> ThamGiasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TieuSuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DienThoai {
            get {
                return this.DienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.DienThoaiField, value) != true)) {
                    this.DienThoaiField = value;
                    this.RaisePropertyChanged("DienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TacGiaID {
            get {
                return this.TacGiaIDField;
            }
            set {
                if ((this.TacGiaIDField.Equals(value) != true)) {
                    this.TacGiaIDField = value;
                    this.RaisePropertyChanged("TacGiaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenTacGia {
            get {
                return this.TenTacGiaField;
            }
            set {
                if ((object.ReferenceEquals(this.TenTacGiaField, value) != true)) {
                    this.TenTacGiaField = value;
                    this.RaisePropertyChanged("TenTacGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebApp.ServiceReference1.ThamGia> ThamGias {
            get {
                return this.ThamGiasField;
            }
            set {
                if ((object.ReferenceEquals(this.ThamGiasField, value) != true)) {
                    this.ThamGiasField = value;
                    this.RaisePropertyChanged("ThamGias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TieuSu {
            get {
                return this.TieuSuField;
            }
            set {
                if ((object.ReferenceEquals(this.TieuSuField, value) != true)) {
                    this.TieuSuField = value;
                    this.RaisePropertyChanged("TieuSu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Collections.Generic.List<WebApp.ServiceReference1.Sach> GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.Sach>> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Chude", ReplyAction="http://tempuri.org/IService1/ChudeResponse")]
        System.Collections.Generic.List<WebApp.ServiceReference1.ChuDe> Chude();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Chude", ReplyAction="http://tempuri.org/IService1/ChudeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.ChuDe>> ChudeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TimkiemSachTheoChude", ReplyAction="http://tempuri.org/IService1/TimkiemSachTheoChudeResponse")]
        System.Collections.Generic.List<WebApp.ServiceReference1.Sach> TimkiemSachTheoChude(int chudeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TimkiemSachTheoChude", ReplyAction="http://tempuri.org/IService1/TimkiemSachTheoChudeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.Sach>> TimkiemSachTheoChudeAsync(int chudeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sanphambanchay", ReplyAction="http://tempuri.org/IService1/SanphambanchayResponse")]
        System.Collections.Generic.List<WebApp.ServiceReference1.Sach> Sanphambanchay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sanphambanchay", ReplyAction="http://tempuri.org/IService1/SanphambanchayResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.Sach>> SanphambanchayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DSLoaiTimKiem", ReplyAction="http://tempuri.org/IService1/DSLoaiTimKiemResponse")]
        System.Collections.Generic.List<WebApp.ServiceReference1.ChuDe> DSLoaiTimKiem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DSLoaiTimKiem", ReplyAction="http://tempuri.org/IService1/DSLoaiTimKiemResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.ChuDe>> DSLoaiTimKiemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Chitietsanpham", ReplyAction="http://tempuri.org/IService1/ChitietsanphamResponse")]
        WebApp.ServiceReference1.Sach Chitietsanpham(int masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Chitietsanpham", ReplyAction="http://tempuri.org/IService1/ChitietsanphamResponse")]
        System.Threading.Tasks.Task<WebApp.ServiceReference1.Sach> ChitietsanphamAsync(int masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPCungLoai1", ReplyAction="http://tempuri.org/IService1/SPCungLoai1Response")]
        WebApp.ServiceReference1.Sach SPCungLoai1(int Sachid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPCungLoai1", ReplyAction="http://tempuri.org/IService1/SPCungLoai1Response")]
        System.Threading.Tasks.Task<WebApp.ServiceReference1.Sach> SPCungLoai1Async(int Sachid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPCungLoai2", ReplyAction="http://tempuri.org/IService1/SPCungLoai2Response")]
        System.Collections.Generic.List<WebApp.ServiceReference1.Sach> SPCungLoai2(int chudeid, int sachid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPCungLoai2", ReplyAction="http://tempuri.org/IService1/SPCungLoai2Response")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.Sach>> SPCungLoai2Async(int chudeid, int sachid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThongTinKhachHang", ReplyAction="http://tempuri.org/IService1/ThongTinKhachHangResponse")]
        System.Collections.Generic.List<WebApp.ServiceReference1.KhachHang> ThongTinKhachHang(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThongTinKhachHang", ReplyAction="http://tempuri.org/IService1/ThongTinKhachHangResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.KhachHang>> ThongTinKhachHangAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KiemtraDk", ReplyAction="http://tempuri.org/IService1/KiemtraDkResponse")]
        bool KiemtraDk(string tendangnhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KiemtraDk", ReplyAction="http://tempuri.org/IService1/KiemtraDkResponse")]
        System.Threading.Tasks.Task<bool> KiemtraDkAsync(string tendangnhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemKhacHang", ReplyAction="http://tempuri.org/IService1/ThemKhacHangResponse")]
        bool ThemKhacHang(string hoten, string diachi, string sodienthoai, string tendangnhap, string matkhau, System.DateTime ngaysinh, bool gioitinh, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemKhacHang", ReplyAction="http://tempuri.org/IService1/ThemKhacHangResponse")]
        System.Threading.Tasks.Task<bool> ThemKhacHangAsync(string hoten, string diachi, string sodienthoai, string tendangnhap, string matkhau, System.DateTime ngaysinh, bool gioitinh, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KiemTraDangNhap", ReplyAction="http://tempuri.org/IService1/KiemTraDangNhapResponse")]
        System.Collections.Generic.List<WebApp.ServiceReference1.KhachHang> KiemTraDangNhap(string tendangnhap, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KiemTraDangNhap", ReplyAction="http://tempuri.org/IService1/KiemTraDangNhapResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.KhachHang>> KiemTraDangNhapAsync(string tendangnhap, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KiemTraDNForm", ReplyAction="http://tempuri.org/IService1/KiemTraDNFormResponse")]
        bool KiemTraDNForm(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KiemTraDNForm", ReplyAction="http://tempuri.org/IService1/KiemTraDNFormResponse")]
        System.Threading.Tasks.Task<bool> KiemTraDNFormAsync(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HienthiSach", ReplyAction="http://tempuri.org/IService1/HienthiSachResponse")]
        System.Collections.Generic.List<WebApp.ServiceReference1.Sach> HienthiSach();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HienthiSach", ReplyAction="http://tempuri.org/IService1/HienthiSachResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.Sach>> HienthiSachAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertSach", ReplyAction="http://tempuri.org/IService1/InsertSachResponse")]
        bool InsertSach(string tensach, int giaban, int chudeID, int nhaxuatbanID, string mota, string hinhbia, int sotrang, int trongluong, System.DateTime ngaycapnhap, int soluongban, bool hethang, int daban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertSach", ReplyAction="http://tempuri.org/IService1/InsertSachResponse")]
        System.Threading.Tasks.Task<bool> InsertSachAsync(string tensach, int giaban, int chudeID, int nhaxuatbanID, string mota, string hinhbia, int sotrang, int trongluong, System.DateTime ngaycapnhap, int soluongban, bool hethang, int daban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateSach", ReplyAction="http://tempuri.org/IService1/UpdateSachResponse")]
        bool UpdateSach(int sachid, string tensach, int giaban, int chudeID, int nhaxuatbanID, string mota, string hinhbia, int sotrang, int trongluong, System.DateTime ngaycapnhap, int soluongban, bool hethang, int daban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateSach", ReplyAction="http://tempuri.org/IService1/UpdateSachResponse")]
        System.Threading.Tasks.Task<bool> UpdateSachAsync(int sachid, string tensach, int giaban, int chudeID, int nhaxuatbanID, string mota, string hinhbia, int sotrang, int trongluong, System.DateTime ngaycapnhap, int soluongban, bool hethang, int daban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSach", ReplyAction="http://tempuri.org/IService1/DeleteSachResponse")]
        bool DeleteSach(int sachid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSach", ReplyAction="http://tempuri.org/IService1/DeleteSachResponse")]
        System.Threading.Tasks.Task<bool> DeleteSachAsync(int sachid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KiemtraTendangnhap", ReplyAction="http://tempuri.org/IService1/KiemtraTendangnhapResponse")]
        System.Collections.Generic.List<WebApp.ServiceReference1.KhachHang> KiemtraTendangnhap(string tendangnhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KiemtraTendangnhap", ReplyAction="http://tempuri.org/IService1/KiemtraTendangnhapResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.KhachHang>> KiemtraTendangnhapAsync(string tendangnhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemDonDathang", ReplyAction="http://tempuri.org/IService1/ThemDonDathangResponse")]
        bool ThemDonDathang(int makh, string tenkh, string diadiem, System.DateTime ngaydathang, double trigia, bool dagiao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemDonDathang", ReplyAction="http://tempuri.org/IService1/ThemDonDathangResponse")]
        System.Threading.Tasks.Task<bool> ThemDonDathangAsync(int makh, string tenkh, string diadiem, System.DateTime ngaydathang, double trigia, bool dagiao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaychitietSach_donDH", ReplyAction="http://tempuri.org/IService1/LaychitietSach_donDHResponse")]
        WebApp.ServiceReference1.Sach LaychitietSach_donDH(int sachid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LaychitietSach_donDH", ReplyAction="http://tempuri.org/IService1/LaychitietSach_donDHResponse")]
        System.Threading.Tasks.Task<WebApp.ServiceReference1.Sach> LaychitietSach_donDHAsync(int sachid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemChitietDonDatHang", ReplyAction="http://tempuri.org/IService1/ThemChitietDonDatHangResponse")]
        bool ThemChitietDonDatHang(int dathangid, int sachid, int soluong, double dongia, double thanhtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemChitietDonDatHang", ReplyAction="http://tempuri.org/IService1/ThemChitietDonDatHangResponse")]
        System.Threading.Tasks.Task<bool> ThemChitietDonDatHangAsync(int dathangid, int sachid, int soluong, double dongia, double thanhtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayKhachHang", ReplyAction="http://tempuri.org/IService1/LayKhachHangResponse")]
        WebApp.ServiceReference1.KhachHang LayKhachHang(string tendangnhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayKhachHang", ReplyAction="http://tempuri.org/IService1/LayKhachHangResponse")]
        System.Threading.Tasks.Task<WebApp.ServiceReference1.KhachHang> LayKhachHangAsync(string tendangnhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPhieuNhap", ReplyAction="http://tempuri.org/IService1/GetPhieuNhapResponse")]
        System.Collections.Generic.List<WebApp.ServiceReference1.PhieuNhap> GetPhieuNhap();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPhieuNhap", ReplyAction="http://tempuri.org/IService1/GetPhieuNhapResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.PhieuNhap>> GetPhieuNhapAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemPhieuNhap", ReplyAction="http://tempuri.org/IService1/ThemPhieuNhapResponse")]
        bool ThemPhieuNhap(System.DateTime ngayNhap, float tongtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemPhieuNhap", ReplyAction="http://tempuri.org/IService1/ThemPhieuNhapResponse")]
        System.Threading.Tasks.Task<bool> ThemPhieuNhapAsync(System.DateTime ngayNhap, float tongtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPhieuNhapCT", ReplyAction="http://tempuri.org/IService1/GetPhieuNhapCTResponse")]
        System.Collections.Generic.List<WebApp.ServiceReference1.PhieuNhapCT> GetPhieuNhapCT(int phieunhapid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPhieuNhapCT", ReplyAction="http://tempuri.org/IService1/GetPhieuNhapCTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.PhieuNhapCT>> GetPhieuNhapCTAsync(int phieunhapid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemChiTietPhieuNhap", ReplyAction="http://tempuri.org/IService1/ThemChiTietPhieuNhapResponse")]
        bool ThemChiTietPhieuNhap(int idphieunhap, int idmasach, float dongia, float thanhtien, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemChiTietPhieuNhap", ReplyAction="http://tempuri.org/IService1/ThemChiTietPhieuNhapResponse")]
        System.Threading.Tasks.Task<bool> ThemChiTietPhieuNhapAsync(int idphieunhap, int idmasach, float dongia, float thanhtien, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThanhTien", ReplyAction="http://tempuri.org/IService1/ThanhTienResponse")]
        float ThanhTien(int maphieunhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThanhTien", ReplyAction="http://tempuri.org/IService1/ThanhTienResponse")]
        System.Threading.Tasks.Task<float> ThanhTienAsync(int maphieunhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePhieuNhap", ReplyAction="http://tempuri.org/IService1/UpdatePhieuNhapResponse")]
        bool UpdatePhieuNhap(int maphieunhap, float thanhtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePhieuNhap", ReplyAction="http://tempuri.org/IService1/UpdatePhieuNhapResponse")]
        System.Threading.Tasks.Task<bool> UpdatePhieuNhapAsync(int maphieunhap, float thanhtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaPhieuNhapCT", ReplyAction="http://tempuri.org/IService1/XoaPhieuNhapCTResponse")]
        bool XoaPhieuNhapCT(int ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaPhieuNhapCT", ReplyAction="http://tempuri.org/IService1/XoaPhieuNhapCTResponse")]
        System.Threading.Tasks.Task<bool> XoaPhieuNhapCTAsync(int ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemsoLuongSach", ReplyAction="http://tempuri.org/IService1/ThemsoLuongSachResponse")]
        bool ThemsoLuongSach(int masach, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemsoLuongSach", ReplyAction="http://tempuri.org/IService1/ThemsoLuongSachResponse")]
        System.Threading.Tasks.Task<bool> ThemsoLuongSachAsync(int masach, int soluong);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApp.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApp.ServiceReference1.IService1>, WebApp.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WebApp.ServiceReference1.Sach> GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.Sach>> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public System.Collections.Generic.List<WebApp.ServiceReference1.ChuDe> Chude() {
            return base.Channel.Chude();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.ChuDe>> ChudeAsync() {
            return base.Channel.ChudeAsync();
        }
        
        public System.Collections.Generic.List<WebApp.ServiceReference1.Sach> TimkiemSachTheoChude(int chudeid) {
            return base.Channel.TimkiemSachTheoChude(chudeid);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.Sach>> TimkiemSachTheoChudeAsync(int chudeid) {
            return base.Channel.TimkiemSachTheoChudeAsync(chudeid);
        }
        
        public System.Collections.Generic.List<WebApp.ServiceReference1.Sach> Sanphambanchay() {
            return base.Channel.Sanphambanchay();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.Sach>> SanphambanchayAsync() {
            return base.Channel.SanphambanchayAsync();
        }
        
        public System.Collections.Generic.List<WebApp.ServiceReference1.ChuDe> DSLoaiTimKiem() {
            return base.Channel.DSLoaiTimKiem();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.ChuDe>> DSLoaiTimKiemAsync() {
            return base.Channel.DSLoaiTimKiemAsync();
        }
        
        public WebApp.ServiceReference1.Sach Chitietsanpham(int masp) {
            return base.Channel.Chitietsanpham(masp);
        }
        
        public System.Threading.Tasks.Task<WebApp.ServiceReference1.Sach> ChitietsanphamAsync(int masp) {
            return base.Channel.ChitietsanphamAsync(masp);
        }
        
        public WebApp.ServiceReference1.Sach SPCungLoai1(int Sachid) {
            return base.Channel.SPCungLoai1(Sachid);
        }
        
        public System.Threading.Tasks.Task<WebApp.ServiceReference1.Sach> SPCungLoai1Async(int Sachid) {
            return base.Channel.SPCungLoai1Async(Sachid);
        }
        
        public System.Collections.Generic.List<WebApp.ServiceReference1.Sach> SPCungLoai2(int chudeid, int sachid) {
            return base.Channel.SPCungLoai2(chudeid, sachid);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.Sach>> SPCungLoai2Async(int chudeid, int sachid) {
            return base.Channel.SPCungLoai2Async(chudeid, sachid);
        }
        
        public System.Collections.Generic.List<WebApp.ServiceReference1.KhachHang> ThongTinKhachHang(string email) {
            return base.Channel.ThongTinKhachHang(email);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.KhachHang>> ThongTinKhachHangAsync(string email) {
            return base.Channel.ThongTinKhachHangAsync(email);
        }
        
        public bool KiemtraDk(string tendangnhap) {
            return base.Channel.KiemtraDk(tendangnhap);
        }
        
        public System.Threading.Tasks.Task<bool> KiemtraDkAsync(string tendangnhap) {
            return base.Channel.KiemtraDkAsync(tendangnhap);
        }
        
        public bool ThemKhacHang(string hoten, string diachi, string sodienthoai, string tendangnhap, string matkhau, System.DateTime ngaysinh, bool gioitinh, string email) {
            return base.Channel.ThemKhacHang(hoten, diachi, sodienthoai, tendangnhap, matkhau, ngaysinh, gioitinh, email);
        }
        
        public System.Threading.Tasks.Task<bool> ThemKhacHangAsync(string hoten, string diachi, string sodienthoai, string tendangnhap, string matkhau, System.DateTime ngaysinh, bool gioitinh, string email) {
            return base.Channel.ThemKhacHangAsync(hoten, diachi, sodienthoai, tendangnhap, matkhau, ngaysinh, gioitinh, email);
        }
        
        public System.Collections.Generic.List<WebApp.ServiceReference1.KhachHang> KiemTraDangNhap(string tendangnhap, string pass) {
            return base.Channel.KiemTraDangNhap(tendangnhap, pass);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.KhachHang>> KiemTraDangNhapAsync(string tendangnhap, string pass) {
            return base.Channel.KiemTraDangNhapAsync(tendangnhap, pass);
        }
        
        public bool KiemTraDNForm(string user, string pass) {
            return base.Channel.KiemTraDNForm(user, pass);
        }
        
        public System.Threading.Tasks.Task<bool> KiemTraDNFormAsync(string user, string pass) {
            return base.Channel.KiemTraDNFormAsync(user, pass);
        }
        
        public System.Collections.Generic.List<WebApp.ServiceReference1.Sach> HienthiSach() {
            return base.Channel.HienthiSach();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.Sach>> HienthiSachAsync() {
            return base.Channel.HienthiSachAsync();
        }
        
        public bool InsertSach(string tensach, int giaban, int chudeID, int nhaxuatbanID, string mota, string hinhbia, int sotrang, int trongluong, System.DateTime ngaycapnhap, int soluongban, bool hethang, int daban) {
            return base.Channel.InsertSach(tensach, giaban, chudeID, nhaxuatbanID, mota, hinhbia, sotrang, trongluong, ngaycapnhap, soluongban, hethang, daban);
        }
        
        public System.Threading.Tasks.Task<bool> InsertSachAsync(string tensach, int giaban, int chudeID, int nhaxuatbanID, string mota, string hinhbia, int sotrang, int trongluong, System.DateTime ngaycapnhap, int soluongban, bool hethang, int daban) {
            return base.Channel.InsertSachAsync(tensach, giaban, chudeID, nhaxuatbanID, mota, hinhbia, sotrang, trongluong, ngaycapnhap, soluongban, hethang, daban);
        }
        
        public bool UpdateSach(int sachid, string tensach, int giaban, int chudeID, int nhaxuatbanID, string mota, string hinhbia, int sotrang, int trongluong, System.DateTime ngaycapnhap, int soluongban, bool hethang, int daban) {
            return base.Channel.UpdateSach(sachid, tensach, giaban, chudeID, nhaxuatbanID, mota, hinhbia, sotrang, trongluong, ngaycapnhap, soluongban, hethang, daban);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateSachAsync(int sachid, string tensach, int giaban, int chudeID, int nhaxuatbanID, string mota, string hinhbia, int sotrang, int trongluong, System.DateTime ngaycapnhap, int soluongban, bool hethang, int daban) {
            return base.Channel.UpdateSachAsync(sachid, tensach, giaban, chudeID, nhaxuatbanID, mota, hinhbia, sotrang, trongluong, ngaycapnhap, soluongban, hethang, daban);
        }
        
        public bool DeleteSach(int sachid) {
            return base.Channel.DeleteSach(sachid);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSachAsync(int sachid) {
            return base.Channel.DeleteSachAsync(sachid);
        }
        
        public System.Collections.Generic.List<WebApp.ServiceReference1.KhachHang> KiemtraTendangnhap(string tendangnhap) {
            return base.Channel.KiemtraTendangnhap(tendangnhap);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.KhachHang>> KiemtraTendangnhapAsync(string tendangnhap) {
            return base.Channel.KiemtraTendangnhapAsync(tendangnhap);
        }
        
        public bool ThemDonDathang(int makh, string tenkh, string diadiem, System.DateTime ngaydathang, double trigia, bool dagiao) {
            return base.Channel.ThemDonDathang(makh, tenkh, diadiem, ngaydathang, trigia, dagiao);
        }
        
        public System.Threading.Tasks.Task<bool> ThemDonDathangAsync(int makh, string tenkh, string diadiem, System.DateTime ngaydathang, double trigia, bool dagiao) {
            return base.Channel.ThemDonDathangAsync(makh, tenkh, diadiem, ngaydathang, trigia, dagiao);
        }
        
        public WebApp.ServiceReference1.Sach LaychitietSach_donDH(int sachid) {
            return base.Channel.LaychitietSach_donDH(sachid);
        }
        
        public System.Threading.Tasks.Task<WebApp.ServiceReference1.Sach> LaychitietSach_donDHAsync(int sachid) {
            return base.Channel.LaychitietSach_donDHAsync(sachid);
        }
        
        public bool ThemChitietDonDatHang(int dathangid, int sachid, int soluong, double dongia, double thanhtien) {
            return base.Channel.ThemChitietDonDatHang(dathangid, sachid, soluong, dongia, thanhtien);
        }
        
        public System.Threading.Tasks.Task<bool> ThemChitietDonDatHangAsync(int dathangid, int sachid, int soluong, double dongia, double thanhtien) {
            return base.Channel.ThemChitietDonDatHangAsync(dathangid, sachid, soluong, dongia, thanhtien);
        }
        
        public WebApp.ServiceReference1.KhachHang LayKhachHang(string tendangnhap) {
            return base.Channel.LayKhachHang(tendangnhap);
        }
        
        public System.Threading.Tasks.Task<WebApp.ServiceReference1.KhachHang> LayKhachHangAsync(string tendangnhap) {
            return base.Channel.LayKhachHangAsync(tendangnhap);
        }
        
        public System.Collections.Generic.List<WebApp.ServiceReference1.PhieuNhap> GetPhieuNhap() {
            return base.Channel.GetPhieuNhap();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.PhieuNhap>> GetPhieuNhapAsync() {
            return base.Channel.GetPhieuNhapAsync();
        }
        
        public bool ThemPhieuNhap(System.DateTime ngayNhap, float tongtien) {
            return base.Channel.ThemPhieuNhap(ngayNhap, tongtien);
        }
        
        public System.Threading.Tasks.Task<bool> ThemPhieuNhapAsync(System.DateTime ngayNhap, float tongtien) {
            return base.Channel.ThemPhieuNhapAsync(ngayNhap, tongtien);
        }
        
        public System.Collections.Generic.List<WebApp.ServiceReference1.PhieuNhapCT> GetPhieuNhapCT(int phieunhapid) {
            return base.Channel.GetPhieuNhapCT(phieunhapid);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApp.ServiceReference1.PhieuNhapCT>> GetPhieuNhapCTAsync(int phieunhapid) {
            return base.Channel.GetPhieuNhapCTAsync(phieunhapid);
        }
        
        public bool ThemChiTietPhieuNhap(int idphieunhap, int idmasach, float dongia, float thanhtien, int soluong) {
            return base.Channel.ThemChiTietPhieuNhap(idphieunhap, idmasach, dongia, thanhtien, soluong);
        }
        
        public System.Threading.Tasks.Task<bool> ThemChiTietPhieuNhapAsync(int idphieunhap, int idmasach, float dongia, float thanhtien, int soluong) {
            return base.Channel.ThemChiTietPhieuNhapAsync(idphieunhap, idmasach, dongia, thanhtien, soluong);
        }
        
        public float ThanhTien(int maphieunhap) {
            return base.Channel.ThanhTien(maphieunhap);
        }
        
        public System.Threading.Tasks.Task<float> ThanhTienAsync(int maphieunhap) {
            return base.Channel.ThanhTienAsync(maphieunhap);
        }
        
        public bool UpdatePhieuNhap(int maphieunhap, float thanhtien) {
            return base.Channel.UpdatePhieuNhap(maphieunhap, thanhtien);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePhieuNhapAsync(int maphieunhap, float thanhtien) {
            return base.Channel.UpdatePhieuNhapAsync(maphieunhap, thanhtien);
        }
        
        public bool XoaPhieuNhapCT(int ma) {
            return base.Channel.XoaPhieuNhapCT(ma);
        }
        
        public System.Threading.Tasks.Task<bool> XoaPhieuNhapCTAsync(int ma) {
            return base.Channel.XoaPhieuNhapCTAsync(ma);
        }
        
        public bool ThemsoLuongSach(int masach, int soluong) {
            return base.Channel.ThemsoLuongSach(masach, soluong);
        }
        
        public System.Threading.Tasks.Task<bool> ThemsoLuongSachAsync(int masach, int soluong) {
            return base.Channel.ThemsoLuongSachAsync(masach, soluong);
        }
    }
}
